In [5]:
import warnings
def warn1(*args,**kwargs):
    pass
warnings.warn=warn1

In [6]:
import pandas as pd
import numpy as np
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report

In [7]:
Dump=pd.read_excel("Flexcube Solution Dump.xlsx")

In [8]:
Dump.head(10)

,Incident: Number,CompanyName,Severity,Queue,Resolution,Category,Client ID,Resolved Date,Opened Date,Closed Date,Resolution Type,Status,Description,Staff,Support Department,Assigned Queue Date,Client Department,Client Manager
0,894193,Virtusa,NaN,Flexcube Support,Already previous modification its rejected . s...,Flexcube -UAE,Krishna Pruthvi,2018-01-31 16:54:00,2018-01-30 14:41:00,2018-02-05 23:02:00,Training/User Understanding Issue,CLOSED,"Not able to edit CIF number as it is in ""Unaut...",Badmaprasath Baskaran,TPS,2018-01-31 11:47:00,RPA,Yogaraajan N E
1,867705,TCS,NaN,Flexcube RTB,data patch executed to reverse the entries on ...,Flexcube -UAE,Saptagiri J,2018-01-21 16:50:00,2018-01-11 17:50:00,2018-01-26 23:03:00,Duplicate,CLOSED,"Hi Team, For below client, on 9th Jan 2018 acc...",Arun Jagannathan,Core Platform,2018-01-16 18:27:00,CCU,Tariq Amer
2,297997,TCS,NaN,Flexcube RTB,Rebate amount is populated properly for the me...,Flexcube -UAE,Ramya Vijayakumar,2016-07-28 16:09:00,2016-07-21 17:16:00,2017-04-12 18:33:00,No Action Taken,CLOSED,EDMS 661765 CIF 012628556 WHEN WE TRIED TO SET...,Jayakeerthana S,Core Platform,2016-07-21 19:17:00,Loans Disbursal,Sheikh Abid Ejaz
3,954289,Mashreq Bank,NaN,Flexcube Support,Customer Account statements are generated from...,Flexcube -UAE,Vanessa Fernandes,2018-03-19 11:36:00,2018-03-12 12:37:00,2018-03-24 23:01:00,FAQ / Knowledge Article,CLOSED,"Dear Team, Islamic accounts have been marked f...",Badmaprasath Baskaran,TPS,2018-03-12 13:10:00,Retail Banking Group,Rosario Fernandes
4,488497,TCS,NaN,Flexcube RTB,on 13-FEB-2017 user unlock and saved the accou...,Flexcube -UAE,Saptagiri J,2017-03-06 10:06:00,2017-03-01 20:13:00,2017-03-21 01:43:00,Training/User Understanding Issue,CLOSED,"Hi All, Below account has been debited of AED ...",Arun Jagannathan,Core Platform,2017-03-05 16:19:00,CCU,Tariq Amer
5,301969,TCS,NaN,Flexcube RTB,"Dear Ramya Vijayakumar, As discussed,Amount du...",Flexcube -UAE,Ramya Vijayakumar,2016-07-26 15:19:00,2016-07-25 15:03:00,2017-04-12 18:30:00,Training/User Understanding Issue,CLOSED,IRIS- 515904 CIF 012756395 recovery 0191000818...,Jayakeerthana S,Core Platform,2016-07-25 20:38:00,Loans Disbursal,Sheikh Abid Ejaz
6,902371,Mashreq Bank Qatar,NaN,Flexcube Support,All 3 MMCs mentioned as part of this ticket ar...,Flexcube -Qatar,Adnan Ahmad,2018-02-05 15:31:00,2018-02-05 10:09:00,2018-02-10 23:02:00,Training/User Understanding Issue,CLOSED,Kindly confirm and advise on below Mashreq Mil...,Badmaprasath Baskaran,TPS,2018-02-05 11:23:00,Retail Banking,Halima Bador S A Alabdulla
7,522779,TCS,NaN,Flexcube RTB,"for that account class ""CDPCUS"" ->""NAUR"" its n...",Flexcube -UAE,Saptagiri J,2017-04-02 17:08:00,2017-04-02 11:32:00,2017-04-19 23:24:00,Training/User Understanding Issue,CLOSED,"Hi All, MRS Rating for the below client is 50 ...",Arun Jagannathan,Core Platform,2017-04-02 15:54:00,CCU,Tariq Amer
8,303782,TCS,NaN,Flexcube RTB,Rebate amount has populated for the mentioned ...,Flexcube -UAE,Ramya Vijayakumar,2016-07-28 15:50:00,2016-07-27 16:03:00,2017-04-12 18:33:00,No Action Taken,CLOSED,Rebate amount is not populating while settling...,Jayakeerthana S,Core Platform,2016-07-27 16:39:00,Loans Disbursal,Sheikh Abid Ejaz
9,889934,Injaz,NaN,Flexcube Support,VAT is enabled in the product OVWO for the INI...,Flexcube -UAE,Prashant Adappa,2018-01-31 15:02:00,2018-01-28 10:08:00,2018-02-05 23:01:00,Training/User Understanding Issue,CLOSED,Transaction under ref 033OVWO180060506. VAT am...,Badmaprasath Baskaran,TPS,2018-01-28 10:31:00,Operations Group,Sohail Iqbal Iqbal

In [9]:
Dump.shape

(15930, 18)

In [10]:
Dump=Dump.drop_duplicates()

In [11]:
Dump.shape

(15930, 18)

**Observation**
- No Duplicates in the records

In [14]:
Dump.isna().sum()
#Dump.isnull().sum()

Incident: Number           0
CompanyName               17
Severity               15853
Queue                      0
Resolution                18
Category                  14
Client ID                  0
Resolved Date            328
Opened Date                0
Closed Date                0
Resolution Type            2
Status                     0
Description                0
Staff                      0
Support Department        11
Assigned Queue Date        0
Client Department          7
Client Manager           100
dtype: int64

###### We Can strightway drop columns with  most no of Nulls

In [15]:
Dump=Dump.drop(columns=['Severity'],axis=1)

In [16]:
Dump.head()

,Incident: Number,CompanyName,Queue,Resolution,Category,Client ID,Resolved Date,Opened Date,Closed Date,Resolution Type,Status,Description,Staff,Support Department,Assigned Queue Date,Client Department,Client Manager
0,894193,Virtusa,Flexcube Support,Already previous modification its rejected . s...,Flexcube -UAE,Krishna Pruthvi,2018-01-31 16:54:00,2018-01-30 14:41:00,2018-02-05 23:02:00,Training/User Understanding Issue,CLOSED,"Not able to edit CIF number as it is in ""Unaut...",Badmaprasath Baskaran,TPS,2018-01-31 11:47:00,RPA,Yogaraajan N E
1,867705,TCS,Flexcube RTB,data patch executed to reverse the entries on ...,Flexcube -UAE,Saptagiri J,2018-01-21 16:50:00,2018-01-11 17:50:00,2018-01-26 23:03:00,Duplicate,CLOSED,"Hi Team, For below client, on 9th Jan 2018 acc...",Arun Jagannathan,Core Platform,2018-01-16 18:27:00,CCU,Tariq Amer
2,297997,TCS,Flexcube RTB,Rebate amount is populated properly for the me...,Flexcube -UAE,Ramya Vijayakumar,2016-07-28 16:09:00,2016-07-21 17:16:00,2017-04-12 18:33:00,No Action Taken,CLOSED,EDMS 661765 CIF 012628556 WHEN WE TRIED TO SET...,Jayakeerthana S,Core Platform,2016-07-21 19:17:00,Loans Disbursal,Sheikh Abid Ejaz
3,954289,Mashreq Bank,Flexcube Support,Customer Account statements are generated from...,Flexcube -UAE,Vanessa Fernandes,2018-03-19 11:36:00,2018-03-12 12:37:00,2018-03-24 23:01:00,FAQ / Knowledge Article,CLOSED,"Dear Team, Islamic accounts have been marked f...",Badmaprasath Baskaran,TPS,2018-03-12 13:10:00,Retail Banking Group,Rosario Fernandes
4,488497,TCS,Flexcube RTB,on 13-FEB-2017 user unlock and saved the accou...,Flexcube -UAE,Saptagiri J,2017-03-06 10:06:00,2017-03-01 20:13:00,2017-03-21 01:43:00,Training/User Understanding Issue,CLOSED,"Hi All, Below account has been debited of AED ...",Arun Jagannathan,Core Platform,2017-03-05 16:19:00,CCU,Tariq Amer

In [17]:
Dump=Dump.dropna()
#Dump=Dump[['Resolution','Resolution Type','Description','Support Department','Client Department']]

In [18]:
Dump.shape

(15461, 17)

#### It has dropped some of the rows which has null values,we can do it

In [28]:
Dump.describe(include='O')

,CompanyName,Queue,Resolution,Category,Client ID,Resolution Type,Status,Description,Staff,Support Department,Client Department,Client Manager
count,15461,15461,15461,15461,15461,15461,15461,15461,15461,15461,15461,15461
unique,55,3,14837,89,2038,19,2,15287,36,3,228,557
top,TCS,Flexcube Support,issue resolved. please check duplicate : IN007...,Flexcube -UAE,Hemant Garg,Training/User Understanding Issue,CLOSED,please change the Mashreq millionaire issuance...,Aditya Rao Aroor Kinni,TPS,Retail Banking Group,Ali Ishaq Mohammed
freq,5605,9315,21,10856,182,4268,15439,7,2506,9824,4108,1167

In [31]:
Array1=Dump.values
Array1[0]

array([894193, 'Virtusa', 'Flexcube Support',
       'Already previous modification its rejected . still not authorized. please authorize them first and then authorize the latest modification.',
       'Flexcube -UAE', 'Krishna Pruthvi',
       Timestamp('2018-01-31 16:54:00'), Timestamp('2018-01-30 14:41:00'),
       Timestamp('2018-02-05 23:02:00'),
       'Training/User Understanding\xa0 Issue', 'CLOSED',
       'Not able to edit CIF number as it is in "Unauthorised" State. On STDCIF Page, after the KYC details have been updated and saved for the Customer with cif number "010351975" by Tarabot4, the particular CIF\'s authorisation status has changed to "unauthorised" status and cannot be modified by anyone. Please advice.',
       'Badmaprasath Baskaran', 'TPS', Timestamp('2018-01-31 11:47:00'),
       'RPA', 'Yogaraajan N E'], dtype=object)

In [33]:
Dump['Client Department'].value_counts()

Retail Banking Group                                     4108
Operations Group                                         1179
Operations                                               1098
Retail Banking                                           1094
CCU                                                       655
Risk Management                                           549
OPS                                                       498
CPC Outward                                               317
Audit, Fraud and Compliance Group                         277
Corporate Affairs                                         270
TECH Bangalore                                            270
Retail Ops - Maintenance & CCRD                           215
CCAM - Retail ( Account Opening & Maintenance )           201
Outward Remittance                                        193
CCAM                                                      191
Open Account TR                                           184
Corporate & Investment Banking Group                      178
CCAM - SME ( Account Opening & Maintenance )              173
International Banking Group                               155
CAM - Retail                                              150
Guarantee Issue                                           132
Credit Control Unit                                       125
MIT                                                       110
Loans Servicing                                           107
CAM                                                        98
Import Lodgement & Doc Check                               97
Import LC Issue                                            91
Secured Assets - Mortgage & Auto                           91
TCS-CCAM                                                   90
Card Ops - Interchange Unit                                87
                                                         ...
CCAM SME Account Maintenance                                1
Ops - FTC                                                   1
RBG                                                         1
REATIL                                                      1
Cards - CE                                                  1
Corporate Platforms - GTS                                   1
IPA                                                         1
Outward Rem                                                 1
Mashreq Matrix                                              1
CAM - SME                                                   1
OPS -CPC Investigation                                      1
Loans Onboarding                                            1
Ayaan                                                       1
Guarantee Issuance                                          1
OPS-CTX-TCS-CPC Investigation                               1
CAD-AP/GRC                                                  1
Credit Information Unit                                     1
Technology Operations - Technology Service Management       1
CRS remediation project                                     1
Robotic Process Automation                                  1
GTT                                                         1
IRIS                                                        1
Egypt- Call Center                                          1
CPC                                                         1
Card Ops - Interchange & Settlements                        1
Overall Trade                                               1
GRC - Reconciliation                                        1
Chargeback/MSU                                              1
CIBG                                                        1
Enterprise Platforms                                        1
Name: Client Department, Length: 228, dtype: int64

In [34]:
Dump['Resolution Type'].value_counts()

Training/User Understanding  Issue    4268
Workaround Suggested                  3211
No Action Taken                       1875
Data Extract                          1440
Data Patch - User                      572
Auto Resolved                          567
Duplicate                              559
FAQ / Knowledge Article                550
Parameter Change                       527
Code Fix                               432
Data Patch - System                    352
Data Patch - System Restriction        295
User Profile Related                   263
Technical Application Issue            154
No Response From User                  119
Data Patch ? Parameter                 104
Infra Related Issue                     88
Unable to Simulate                      77
Change Request                           8
Name: Resolution Type, dtype: int64

In [58]:
Dump1=Dump[['Description','Resolution Type']]

In [59]:
Dump1.head()

,Description,Resolution Type
0,"Not able to edit CIF number as it is in ""Unaut...",Training/User Understanding Issue
1,"Hi Team, For below client, on 9th Jan 2018 acc...",Duplicate
2,EDMS 661765 CIF 012628556 WHEN WE TRIED TO SET...,No Action Taken
3,"Dear Team, Islamic accounts have been marked f...",FAQ / Knowledge Article
4,"Hi All, Below account has been debited of AED ...",Training/User Understanding Issue

In [60]:
#Dump1.isna().sum()
Dump1.isnull().sum()

Description        0
Resolution Type    0
dtype: int64

In [61]:
Dump1.shape

(15461, 2)

In [62]:
list_nonchar=['_','-','[',']',':',')','#','~','(','.',',','\"','\'','/','{','}','%','?','0','1','2','3','4','5','6','7','8','9','>',
'<',
';',
'@',
'&',
'+',
'$',
'=',
'=*^^',
'=*',
'*']

In [63]:
def replace(list_nonchar):
    for char in list_nonchar:
        Dump1['Description']=Dump1['Description'].apply(lambda x : x.replace(char,''))

In [64]:
replace(list_nonchar)

In [65]:
Dump1.head()

,Description,Resolution Type
0,Not able to edit CIF number as it is in Unauth...,Training/User Understanding Issue
1,Hi Team For below client on th Jan accrued de...,Duplicate
2,EDMS CIF WHEN WE TRIED TO SETTLE OLD LOAN RE...,No Action Taken
3,Dear Team Islamic accounts have been marked fo...,FAQ / Knowledge Article
4,Hi All Below account has been debited of AED ...,Training/User Understanding Issue

In [49]:
def fun1(x):
    return x.lower()

In [52]:
Dump1["Description"]=Dump1.Description.apply(fun1)

In [66]:
#def fun2(x):
#    return x.lower()

In [67]:
#Dump1["Description"]=Dump1.Description.apply(lambda x : fun2(x))

In [53]:
#Dump1['Description']=Dump1['Description'].apply(lambda x : x.lower())

In [68]:
Dump1.head()

,Description,Resolution Type
0,not able to edit cif number as it is in unauth...,Training/User Understanding Issue
1,hi team for below client on th jan accrued de...,Duplicate
2,edms cif when we tried to settle old loan re...,No Action Taken
3,dear team islamic accounts have been marked fo...,FAQ / Knowledge Article
4,hi all below account has been debited of aed ...,Training/User Understanding Issue

In [70]:
stemmer=PorterStemmer()
wordnet_lemmatizer=WordNetLemmatizer()

In [71]:
#Dump2=Dump1

In [82]:
"""def preprocess(document):
    words1=word_tokenize(document)
    words1=[word for word in words1 if word not in stopwords.words("english")]
    words1=[wordnet_lemmatizer.lemmatize(word,pos='v') for word in words1]
    words1=[stemmer.stem(word) for word in words1]
    document=" ".join(words1)
    return document"""

'def preprocess(document):\n    words1=word_tokenize(document)\n    words1=[word for word in words1 if word not in stopwords.words("english")]\n    words1=[stemmer.stem(word) for word in words1]\n    words1=[wordnet_lemmatizer.lemmatize(word,pos=\'v\') for word in words1]\n    document=" ".join(words1)\n    return document'

In [80]:
#Dump2['Description']=Dump2['Description'].apply(lambda x : preprocess(x))

In [81]:
#Dump2.head()

,Description,Resolution Type
0,abl edit cif number unauthoris state stdcif pa...,Training/User Understanding Issue
1,hi team client th jan accru debit interest set...,Duplicate
2,edm cif tri settl old loan rebat amount show t...,No Action Taken
3,dear team islam account mark account close how...,FAQ / Knowledge Article
4,hi account debit a drod account client gulf de...,Training/User Understanding Issue

In [87]:
def preprocess(document,lemm=True):
    words=word_tokenize(document)
    words=[word for word in words if word not in stopwords.words('english')]
    if lemm:
        words=[wordnet_lemmatizer.lemmatize(word,pos='v') for word in words]
    else:
        words=[stemmer.stem(word) for word in words]
    document=" ".join(words)
    return document

In [88]:
Dump1['Description']=Dump1['Description'].apply(lambda x : preprocess(x))

In [43]:
Dump1

,Description,Resolution Type
0,able edit cif number unauthorised state stdcif...,Training/User Understanding Issue
1,hi team client th jan accrue debit interest se...,Duplicate
2,edms cif try settle old loan rebate amount sho...,No Action Taken
3,dear team islamic account mark account close h...,FAQ / Knowledge Article
4,hi account debit aed drod account client gulf ...,Training/User Understanding Issue
5,iris cif recovery old loan settle old loan reb...,Training/User Understanding Issue
6,kindly confirm advise mashreq millionaire cert...,Training/User Understanding Issue
7,hi mrs rat client naur update mrs client naur ...,Training/User Understanding Issue
8,rebate amount populate settle old loan iris ci...,No Action Taken
9,transaction ref ovwo vat amount deduct system ...,Training/User Understanding Issue
10,hi client system debit aed credit customer wan...,Training/User Understanding Issue
11,rebate amount populate settle old loan iris re...,No Action Taken
12,dear team try withdraw money itm account itm r...,Training/User Understanding Issue
13,dear unable update drod interest client get er...,Data Patch - User
14,try fix emi amount islamic case schedule show ...,Training/User Understanding Issue
15,customer pay local credit card bill payment mo...,Workaround Suggested
16,hi client gerfacad report outstanding line id ...,Duplicate
17,authorize postponement mention error throw sys...,No Action Taken
18,team unable cancel mashreq millionaire ref mmc...,Code Fix
19,hi client gerfacal report outstanding line id ...,Duplicate
20,authorize postponement branch throw follow err...,No Action Taken
21,kindly provide compete detail cif cm name mobi...,Training/User Understanding Issue
22,hi unable release limit joint utilizer client ...,Workaround Suggested
23,authorize loan branch throw follow error error...,No Action Taken
24,customer block amount account description kind...,Training/User Understanding Issue
25,hi drod charge july month account business wan...,Training/User Understanding Issue
26,authorize loan br throw follow error principal...,No Action Taken
27,whenever statement generation request make eas...,Training/User Understanding Issue
28,hi client outstanding nil per flex gerfacad re...,Data Patch - User
29,authorize resheduling loan branch throw follow...,Training/User Understanding Issue
...,...,...
15900,kindly share schedule detail mention case,Workaround Suggested
15901,anubhav aggarwal mention customer part dds cas...,Workaround Suggested
15902,dear team kildy provide complete loan statemen...,Workaround Suggested
15903,per flexcube bullet payment appear end loan te...,Training/User Understanding Issue
15904,loan ac sina mahdi ghaderi esfahani customers ...,Unable to Simulate
15905,loan ac lei zhang fund available current accou...,Workaround Suggested
15906,gts bo eod along bmw extraction delay uae core...,Technical Application Issue
15907,hi flexcube team please share us cif ids custo...,Data Extract
15908,hi team dob create account cif use neo neo cif...,Training/User Understanding Issue
15909,dear team kindly provide us list ftc users log...,Data Extract
15910,dear team difference still appear bis report a...,Workaround Suggested
15911,hi get error process transaction bill module b...,Parameter Change
15912,hi bill ref sblc lc ref sblc unable liqudidate...,FAQ / Knowledge Article
15913,hi unable liquidate bill due system throw over...,Training/User Understanding Issue
15914,pls inform difference aed account come flex re...,FAQ / Knowledge Article
15915,team tric loan due nov customer try settle onl...,FAQ / Knowledge Article
15916,description request need help obtain total amo...,Data Extract
15917,hi arun discuss please change next liquidation...,Duplicate
15918,unable close mention account contract find isa...,Training/User Understanding Issue
15919,dear team need assistance know check balance a...,FAQ / Knowledge Article
15920,user unable reopen account number reason accou...,Training/User Understanding Issue
15921,certificate mmcmmc two certificate block colla...,FAQ / Knowledge Article
15922,dear team cheque stop payments do flexcube how...,FAQ / Knowledge Article
15923,account show debit balance drop facility liqui...,FAQ / Knowledge Article
15924,kindly delete request cheque book could delete...,No Action Taken
15925,hi team loan book obu branch loan book th jan ...,Training/User Understanding Issue
15926,dear team kindly provide drod interest calcula...,Training/User Understanding Issue
15927,dear team kindly provide drod calculation acco...,Training/User Understanding Issue
15928,dear team per account internal account th mar ...,No Action Taken
15929,dear team able map od account number gescifmp ...,Data Patch - System Restriction

In [108]:
Word_dist=pd.DataFrame(pd.Series((" ".join(Dump1.Description)).split()).value_counts())

In [109]:
Word_dist

                             0
account                  12025
pleas                     8102
error                     6384
kindli                    5185
custom                    4939
date                      3746
loan                      3715
cif                       3679
amount                    3658
team                      3625
system                    3444
transact                  3387
check                     3188
charg                     3096
close                     2953
detail                    2760
number                    2746
dear                      2657
id                        2621
code                      2618
ac                        2614
unabl                     2558
debit                     2392
fail                      2320
need                      2262
get                       2254
provid                    2253
valu                      2152
ref                       1966
refer                     1927
...                        ...
uaepg                        1
kahangi                      1
england                      1
iagandhidham                 1
teknokraft                   1
paymentsfor                  1
refmdc                       1
reuir                        1
kor                          1
qatarrep                     1
teturn                       1
dirct                        1
tagsdeal                     1
spotonlin                    1
byiram                       1
sarwat                       1
amunt                        1
shaju                        1
athour                       1
settleprovid                 1
selimaj                      1
cbakwtmbben                  1
almeida                      1
breackup                     1
leasehold                    1
crop                         1
vlaeu                        1
expiredmbcerrordescript      1
refqtw                       1
kiindli                      1

[22043 rows x 1 columns]

In [112]:
#Word_dist.to_excel("Mash_req.xlsx")
#Word_dist.to_excel("DF_Data.xlsx")

In [113]:
#modelling

In [114]:
X_train,X_test,Y_train,Y_test=train_test_split(Dump1['Description'],Dump1['Resolution Type'],test_size=0.25,random_state=300)

In [116]:
def tokenizer(Description):
    tokens = word_tokenize(Description)
    tokens = [token for token in tokens if token not in stopwords.words('english')]
    tokens = [stemmer.stem(wordnet_lemmatizer.lemmatize(token)) for token in tokens]
    return tokens

In [117]:
TFIDF = TfidfVectorizer(stop_words='english', tokenizer = tokenizer, preprocessor=preprocess)

In [118]:
training_data = TFIDF.fit_transform(X_train)

In [119]:
training_output = Y_train

In [120]:
rf_mod = RandomForestClassifier(n_estimators=150)

In [121]:
rf_mod.fit(training_data,training_output)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [122]:
test_data=X_test.values

In [123]:
result=rf_mod.predict(TFIDF.transform(test_data))

In [124]:
testing_data=Y_test.values

In [128]:
accuracy_score(result,testing_data)

0.39549922400413867

In [129]:
print(classification_report(result,testing_data))

                                    precision    recall  f1-score   support

                     Auto Resolved       0.09      0.39      0.15        31
                    Change Request       0.00      0.00      0.00         0
                          Code Fix       0.08      0.50      0.13        16
                      Data Extract       0.71      0.69      0.70       365
               Data Patch - System       0.04      0.40      0.07        10
   Data Patch - System Restriction       0.00      0.00      0.00         4
                 Data Patch - User       0.24      0.65      0.35        54
            Data Patch ? Parameter       0.00      0.00      0.00         0
                         Duplicate       0.09      0.31      0.14        42
           FAQ / Knowledge Article       0.07      0.37      0.11        27
               Infra Related Issue       0.00      0.00      0.00         1
                   No Action Taken       0.08      0.32      0.13       122
             No Response From User       0.00      0.00      0.00         2
                  Parameter Change       0.49      0.82      0.62        79
       Technical Application Issue       0.00      0.00      0.00         7
Training/User Understanding  Issue       0.74      0.36      0.48      2179
                Unable to Simulate       0.00      0.00      0.00         1
              User Profile Related       0.25      0.56      0.35        25
              Workaround Suggested       0.38      0.33      0.35       901

                         micro avg       0.40      0.40      0.40      3866
                         macro avg       0.17      0.30      0.19      3866
                      weighted avg       0.59      0.40      0.45      3866